jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /game-store
      session:
         timeout: 21600s

spring:
   h2:
      console:
         enabled: true
         path: /h2
         settings:
            trace: true
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:~/biblioteca
      username: sa
      password: 
      hikari:
         poolName: pool
